name: wechat_assets_picker
description: An assets picker which looks like the one in WeChat, support multi asset pick from device.
version: 1.0.0
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^0.7.1
  pedantic: ^1.8.0+1
  photo_manager: ^0.5.0
  provider: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true