name: wechat_assets_picker
description: An assets picker which looks like the one in WeChat, based on `photo_manager` and `extended_image`.
version: 1.0.0
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^0.7.1
  extended_image_library: any
  photo_manager: ^0.5.0
  provider: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
